# Generated by Django 5.0.6 on 2024-05-22 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('cor', models.CharField(choices=[('Azul', 'Azul'), ('Vermelho', 'Vermelho'), ('Roxo', 'Roxo'), ('Laranja', 'Laranja'), ('Amarelo', 'Amarelo'), ('Verde', 'Verde'), ('Preto', 'Preto'), ('Ciano', 'Ciano')], default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=180)),
                ('url', models.URLField(default='')),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='soloFlix.categoria')),
            ],
        ),
    ]
